# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphicsYoutube.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(487, 318)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 471, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("image: url(:/Youtube/Youtube.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.le_Caminho = QtWidgets.QLineEdit(self.centralwidget)
        self.le_Caminho.setGeometry(QtCore.QRect(100, 200, 381, 20))
        self.le_Caminho.setObjectName("le_Caminho")
        self.pb_Caminho = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Caminho.setGeometry(QtCore.QRect(10, 200, 81, 23))
        self.pb_Caminho.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pb_Caminho.setObjectName("pb_Caminho")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 230, 101, 71))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 99, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_Mp4 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.rb_Mp4.setFont(font)
        self.rb_Mp4.setObjectName("rb_Mp4")
        self.verticalLayout_2.addWidget(self.rb_Mp4)
        self.rb_Mp3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.rb_Mp3.setFont(font)
        self.rb_Mp3.setObjectName("rb_Mp3")
        self.verticalLayout_2.addWidget(self.rb_Mp3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.cb_Video = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_Video.setGeometry(QtCore.QRect(120, 242, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.cb_Video.setFont(font)
        self.cb_Video.setObjectName("cb_Video")
        self.pb_Download = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Download.setGeometry(QtCore.QRect(330, 230, 151, 71))
        self.pb_Download.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pb_Download.setObjectName("pb_Download")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(120, 275, 211, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.le_Link = QtWidgets.QLineEdit(self.centralwidget)
        self.le_Link.setGeometry(QtCore.QRect(10, 170, 471, 20))
        self.le_Link.setObjectName("le_Link")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 148, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.pb_Caminho.setText(_translate("MainWindow", "Caminho"))
        self.rb_Mp4.setText(_translate("MainWindow", "Mp4"))
        self.rb_Mp3.setText(_translate("MainWindow", "Mp3"))
        self.cb_Video.setText(_translate("MainWindow", "Video"))
        self.pb_Download.setText(_translate("MainWindow", "Download"))
        self.label_2.setText(_translate("MainWindow", "Link para Download:"))

import Design.LogoYoutube
